import streamlit as st
from langchain_core.messages import SystemMessage
from langchain_core.prompts import ChatPromptTemplate, HumanMessagePromptTemplate
from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_core.output_parsers import StrOutputParser
from langchain_community.document_loaders import PDFMinerLoader
from langchain_text_splitters import NLTKTextSplitter
from langchain_google_genai import GoogleGenerativeAIEmbeddings
from langchain_community.vectorstores import Chroma
from langchain_core.runnables import RunnablePassthrough

# create a gemini_key.text and paste ur key their
with open('gemini_key.txt') as f: 
    KEY = f.read()

# Define Streamlit title and header
st.title("✨ RAG SYSTEM ✨")
st.header("I'm your A.I Assistant you can ask me any questions related to the paper - Leave No Context Behind.")

# getting the input from  user input
user_input = st.text_area("Type your Question or topic to be discuss.")

# button to trigger answer generation
if st.button("Results"):
    st.balloons()
    # now , define chat prompt template
    chat_template = ChatPromptTemplate.from_messages([
        SystemMessage(content="""Hey there! I'm your friendly AI assistant. 
        I'm here to provide you with insightful answers based on your questions and context."""),
        HumanMessagePromptTemplate.from_template("""Let's uncover some insights together!
        Context:
        {context}
        
        Your Question: 
        {question}
        
        My Response: """)
    ])


    # now loading Google Generative AI model
    chat_model = ChatGoogleGenerativeAI(google_api_key=KEY, model="gemini-1.5-pro-latest")

    # the StrOutputParser is used to parse the output generated by the conversational model (in this case, the Google Generative AI model) into a string format.
    output_parser = StrOutputParser()

    # now defining the pdf loader
    pdf_loader = PDFMinerLoader(r"RAG-ResearchPaper-2404.07143.pdf")
    pdf_docs = pdf_loader.load()

    # split PDF documents into chunks
    text_splitter = NLTKTextSplitter(chunk_size=500, chunk_overlap=100)
    chunks = text_splitter.split_documents(pdf_docs)

    # create embeddings for the chunks
    embedding_model = GoogleGenerativeAIEmbeddings(google_api_key=KEY, model="models/embedding-001")
    db = Chroma.from_documents(chunks, embedding_model, persist_directory="./my_chroma_db_")

    # define retriever and format docs function
    retriever = db.as_retriever(search_kwargs={"k": 5})
    def format_docs(docs):
        return "\n\n".join(doc.page_content for doc in docs)

    # define RAG chain
    rag_chain = (
        {"context": retriever | format_docs, "question": RunnablePassthrough()}
        | chat_template
        | chat_model
        | output_parser
    )

    # now invoke RAG chain to generate answer
    response = rag_chain.invoke(user_input)

    # display answer
    st.subheader("Question")
    st.title(user_input)
    st.subheader("Answer:")
    st.write(response)

if st.button("Clear"):
    st.snow()
    user_input = " "  # Reset user input
    response = ""     # Clear previous result